export default {
  slug: 'product-design',
  title: 'Product design & development',
  href: '/Solution/product-design.html',
  studioIntro: {
    label: 'Product Design',
    heading: ['Designed for people.', 'Built for'],
    accent: 'growth.',
    lead: ['Exceptional UX.', 'Meaningful business impact.'],
    body: 'Since 2013, we’ve helped large enterprises, government departments and startups turn complex challenges into intuitive digital products. We combine research, design and development to create experiences that drive user adoption and business growth.',
    clientLabel: 'Selected clients & collaborators',
    clients: ['Adobe', 'Innodata', '1VALET', 'RealDecoy', 'ISED', 'CBSA'],
  },
  featuredProjects: [
    {
      slug: 'innodata',
      label: 'Enterprise workflows',
      category: 'Innodata / Custom enterprise software',
      heading: ['Complex workflows.', 'Clearer experiences.'],
      description: 'Enterprise software that helps financial researchers and analysts navigate complex information and tasks.',
      challenge: 'Simplify task flows across search, editorial, validation and data integration.',
      contribution: 'UX design and product strategy for the Admin Kit, in collaboration with Zephus Limited.',
      media: 0,
    },
    {
      slug: '1valet',
      label: 'Connected living',
      category: '1VALET / Smart building platform',
      heading: ['A better way', 'to come home.'],
      description: 'Connecting smart access, resident apps and property management in one building platform.',
      challenge: 'Make a connected building feel simple to the people who live in it and the teams who run it.',
      contribution: 'Product strategy, experience design and development, from the MVP through product handover.',
      media: 0,
    },
    {
      slug: 'mobile-app',
      label: 'Consumer experiences',
      category: '100 / Consumer / iOS',
      heading: ['A conversation.', 'More possibilities.'],
      description: 'A personal survey app that turns an iMessage conversation into quick feedback from friends.',
      challenge: 'Make sharing items and gathering feedback feel natural inside an iMessage conversation.',
      contribution: 'Product design and development, UX/UI design for iOS and go-to-market strategy.',
      media: 0,
    },
    {
      slug: 'spectrum-management-platform',
      label: 'Public sector',
      category: 'ISED / Spectrum management platform',
      heading: ['A national platform.', 'A clearer experience.'],
      description: 'Supporting the modernization of how Canada manages and regulates radio spectrum through the Spectrum Cloud platform.',
      challenge: 'Evaluate the final prototype through a nationwide user trial before moving into production.',
      contribution: 'UX research, product strategy and UX design supporting the Spectrum and Telecommunications Sector.',
      media: 0,
    },
  ],
  heroMedia: { video: '/assets/video-background/hx1-product-v2.mp4', poster: '/assets/video-background/hx1-product-v2-poster.jpg' },
  heroLead: 'We combine human-centred design with AI-accelerated development to create exceptional',
  heroLeadLines: ['We combine human-centred design with', 'AI-accelerated development to create exceptional'],
  heroEndings: ['Platforms.', 'Mobile apps.', 'Applications.'],
};
