import {verticals,verticalHref} from './verticals.mjs';
import {projects,videoProjects} from './site-data.mjs';
import {wheelProjects,homeSolutions,homeDisciplines,homeSpotlights} from './home-content.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const project=slug=>projects.find(p=>p.slug===slug);
function img(src,alt,cls='',eager=false){let variants='';if(src.includes('framerusercontent.com'))variants=` srcset="${[512,1024,1600].map(n=>{const u=new URL(src);u.searchParams.set('scale-down-to',n);return `${esc(u.href)} ${n}w`}).join(', ')}" sizes="(max-width:760px) 90vw, 55vw"`;return `<img class="${cls}" src="${esc(src)}"${variants} alt="${esc(alt)}" width="1600" height="900" loading="${eager?'eager':'lazy'}" decoding="async">`}
const link=(href,t,cls='home-link')=>`<a class="${cls}" href="${href}">${t}<span aria-hidden="true">↗</span></a>`;
export function homeBody(){
 const press=project('press'),film=videoProjects[0],filmId=film.src.match(/vi_webp\/([^/]+)/)[1];
 return `<section class="home-opening home-band band-black" data-tone="dark">
 <div class="home-hero container opening-scene"><div class="opening-copy"><p class="hero-kicker">We craft cutting-edge digital experiences for leading brands by seamlessly blending AI, design, and technology.</p><h1 class="rotating-headline"><span class="home-sr">Design, Video, UX, Generative AI, Development and Branding.</span><span class="headline-window" aria-hidden="true"><span class="headline-word" data-headline-word>Design<span class="headline-period">.</span></span></span></h1></div>
 <div class="opening-spotlights" aria-label="Featured projects">${homeSpotlights.map((spot,i)=>{const f=spot.film!==undefined?videoProjects[spot.film]:null,p=f?null:project(spot.slug),id=f?f.src.match(/vi_webp\/([^/]+)/)[1]:null,src=f?f.src:spot.media!==undefined?p.media[spot.media].src:p.thumbnail,title=f?f.title:p.shortClient||p.client;return `<a class="opening-project" data-spotlight-word="${esc(spot.word)}" href="${f?`https://www.youtube.com/watch?v=${id}`:`/projects/${p.slug}/`}"${f?` data-home-film="${id}"`:''} aria-label="${esc(f?`Play ${title}`:`Explore ${title} — ${spot.caption}`)}"${i?' hidden inert aria-hidden="true"':''}><div class="opening-frame"><div class="opening-image${spot.crop?' opening-image-editorial':''}">${spot.crop?`<img src="${esc(src)}" alt="Hinton Press — Australian Open editorial spread" width="2500" height="1096" loading="lazy" decoding="async">`:img(src,f?`${title} — film still`:p.alt,'',i===0)}</div></div><span class="opening-project-caption"><span>${esc(title)}</span><span>${esc(spot.caption)} <span aria-hidden="true">${f?'▶':'↗'}</span></span></span></a>`}).join('')}<span class="opening-progress-track" aria-hidden="true"><span class="opening-progress"></span></span></div>
 <div class="home-hero-bottom"><a href="#selected-work">Explore the work <span aria-hidden="true">↓</span></a></div></div>
 <div class="wheel-track" id="selected-work" data-wheel><div class="wheel-pin"><div class="wheel-heading container"><div><h2>Good thinking.<br>Real-world work.</h2></div></div>
 <div class="wheel-viewport" role="region" aria-label="Selected project collection" tabindex="0"><div class="wheel-cards">${wheelProjects.map((c,i)=>{const p=project(c.slug);return `<a class="wheel-card" data-wheel-card href="/projects/${p.slug}/" style="--card-color:${c.color}">${img(p.thumbnail,p.alt,'wheel-image',i<2)}<span class="wheel-shade"></span><span class="wheel-card-top"><strong>${esc(p.shortClient||p.client)}</strong><span>${String(i+1).padStart(2,'0')}</span></span><span class="wheel-card-bottom"><span class="wheel-discipline">${c.discipline}</span><span class="wheel-title">${c.title}</span><span class="wheel-open" aria-hidden="true">↗</span></span></a>`}).join('')}</div></div><div class="wheel-bottom container">${link('/projects/','View all work')}</div><p class="home-sr" role="status" data-wheel-status></p></div></div></section>
 <section class="home-band band-white studio-introduction" id="studio-intro" data-tone="light"><div class="container"><div class="home-intro-grid"><h2>Different perspectives.<br>One shared<br><em>curiosity.</em></h2><div><p class="home-lead">Good work begins with a better question.</p><p>We bring strategy, design, technology and storytelling into the same conversation. It lets us look at a challenge from more than one angle—and carry an idea through to the details that make it work.</p>${link('/Studio/','Meet HintonX')}</div></div><div class="home-clients"><span class="home-small">Selected collaborations & projects</span><div>${['1valet','innodata','press','social-platform','mobile-app','spectrum-management-platform','canada-border-services-agency'].map(slug=>{const p=project(slug);return `<a href="/projects/${slug}/">${esc(p.shortClient||p.client)}</a>`}).join('')}</div></div></div></section>
 <section class="home-band band-black home-solutions" id="solutions" data-tone="dark"><div class="container"><div class="home-section-title"><h2>What do you<br>want to change?</h2></div><div class="solutions-workbench"><div class="solution-choices">${homeSolutions.map((s,i)=>`<details class="home-solution" id="solution-${s.id}"${i===0?' open':''}><summary><span>0${i+1}</span><h3>${s.title}</h3><span class="home-plus" aria-hidden="true"></span></summary><div class="solution-copy"><p>${s.body}</p><span class="home-small">${s.tags}</span>${link('/projects/'+s.slug+'/','Explore related work')}</div></details>`).join('')}</div><div class="solution-art" aria-label="Related project preview">${homeSolutions.map((s,i)=>{const p=project(s.slug);return `<a class="solution-preview" data-solution-preview="solution-${s.id}" href="/projects/${s.slug}/"${i?' hidden':''}>${img(p.thumbnail,p.alt)}<span><strong>${esc(p.shortClient||p.client)}</strong><span>${esc(p.title)} ↗</span></span></a>`}).join('')}</div></div></div></section>
 <section class="home-band band-white home-capabilities" id="services" data-tone="light"><div class="container"><div class="home-section-title"><h2>From the first idea<br>to the final detail.</h2></div><div class="service-accordions">${homeDisciplines.map((s,i)=>`<details class="home-service" id="${s.id}"${i===0?' open':''}><summary><span class="service-number">0${i+1}</span><h3>${s.title}</h3><span class="home-plus" aria-hidden="true"></span></summary><div class="home-service-body"><h4>${s.intro}</h4><div><p>${s.body}</p>${s.note?`<p class="service-note">${s.note}</p>`:''}${link(verticalHref(verticals.find(v=>v.service===s.id)),'Explore '+s.title)}</div><ul>${s.items.map(t=>`<li>${t}</li>`).join('')}</ul></div></details>`).join('')}</div></div></section>
 <section class="home-band band-black home-cinema" id="film" data-tone="dark"><div class="container"><div class="home-section-title"><h2>Some stories<br>need to move.</h2>${link('/matiadosen/','Explore the films')}</div><a class="home-film-play" href="https://www.youtube.com/watch?v=${filmId}" data-home-film="${filmId}" aria-label="Play ${esc(film.title)}">${img(film.src,`${film.title} — film still`)}<span class="home-film-overlay"></span><span class="home-film-info"><span>Opening sequence teaser</span><strong>${film.title}</strong></span><span class="home-film-button"><span aria-hidden="true">▶</span> Play film</span></a></div></section>
 <section class="home-band band-white home-feature" id="featured-project" data-tone="light"><div class="container"><div class="feature-layout"><a class="feature-art" href="/projects/press/">${img(press.media[1].src,'Hinton Press — editorial layouts and book design')}<span>Brand / Editorial / Digital <span aria-hidden="true">↗</span></span></a><div class="feature-story-copy"><h2>For the love<br>of the game.</h2><p class="home-lead">An identity and publishing experience built around the stories of sport.</p><details open><summary>The challenge <span class="home-plus" aria-hidden="true"></span></summary><p>Bring the character and detail of sports publishing into one connected brand, book and shopping experience.</p></details><details><summary>The work <span class="home-plus" aria-hidden="true"></span></summary><p>Brand development, editorial and book design, and e-commerce design and implementation.</p></details>${link('/projects/press/','Read the full story')}</div></div></div></section>
 <section class="home-band band-black home-invitation" id="start-a-project" data-tone="dark"><div class="container"><div><h2>Have something<br>in mind?</h2>${link('/Contact/','Let’s make it happen','home-contact-button')}</div><p>An idea, a challenge, a possibility.<br>Let’s start a conversation.</p></div></section>
 <dialog id="home-film-dialog" aria-labelledby="home-film-title"><div class="home-film-toolbar"><h2 id="home-film-title">${film.title}</h2><button data-close-home-film aria-label="Close film">Close ×</button></div><div data-home-film-mount></div><a href="https://www.youtube.com/watch?v=${filmId}" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></dialog>`;
}
