import {verticals,verticalHref} from './verticals.mjs';
export const site = {
  name: "HintonX",
  year: "2025",
  navigation: [
    { label: "Work", href: "/projects/" },
    { label: "Services", intro: "Explore the work by discipline.", children: verticals.map(v=>({label:v.title,href:verticalHref(v),note:''})) },
    { label: "Contact", href: "/Contact/" },
    { label: "Start a project", href: "/Contact/", button: true },
  ],
  socials: [
    { label: "Linkedin", href: "https://www.linkedin.com/in/tonydosen" },
    { label: "Instagram", href: "https://www.instagram.com/tonydosen/" },
    { label: "X", href: "https://x.com/TonyDosen" },
  ],
};

export const projects = [
  {
    slug: "mobile-app",
    client: "100",
    title: "iMessage App",
    thumbnail: "https://framerusercontent.com/images/dbryH8RnqXV8XDzazDaXq1ts.png?scale-down-to=2048&width=2500&height=1326",
    alt: "100 iMessage App",
    tagline: "Fun Feedback from Friends",
    description: "HintonX collaborated with Ottawa-based tech innovators to create a personal survey app designed for iMessage. The app allows users to seamlessly share items in chat and invite others to “compare,” “score,” or react with their feelings—turning conversations into quick, engaging feedback moments.",
    services: ["Product Design & Development", "UX/UI Design for iOS", "Go-to-Market Strategy"],
    industries: "Mobile Apps / Social Media / Consumer Tech",
    date: "2019–2022",
    outcome: "The project earned “App of the Day” recognition on the Apple App Store and attracted interest from major social media platforms, influencing the integration of similar feedback features in their ecosystems.",
    media: [
      { src: "https://i.ytimg.com/vi_webp/3hpwgJC-90w/maxresdefault.webp", kind: "video-poster" },
      { src: "https://framerusercontent.com/images/1Ies3TeNRFqHWihsNHdfYqWnpY.png?scale-down-to=2048&width=2500&height=1326", bleed: true },
      { src: "https://framerusercontent.com/images/NfHgF3mh0k93qdLjRcg0sT8OA0Q.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/2iNWjxWo0nZtLIsCwx3zL6Mjxo.png?width=2500&height=1326" },
    ],
  },
  {
    slug: "press",
    client: "Hinton Press",
    title: "A Global Publisher of Sports Excellence",
    thumbnail: "https://framerusercontent.com/images/n3fD5MnskRYhTYc41ZDXNzluc2E.png?scale-down-to=2048&width=2500&height=1326",
    alt: "Hinton Press books and ecommerce",
    tagline: "A Global Publisher of Sports Excellence",
    description: "Hinton Press is a specialist sports publisher creating premium almanacs and collector editions that document the defining moments of each season. With more than 10 titles published and readers in 65+ countries worldwide, each book combines in-depth research, tailored statistics, editorial precision, and refined design—preserving greatness long after the final match is played.",
    services: ["Brand", "E-Commerce Design & Implementation", "Editorial & Book Design"],
    industries: "Publishing / Sports Media",
    date: "June 2025",
    outcome: "Our work has earned international recognition—including being described by Wimbledon Radio as “the best sports book ever made.” Hinton Press continues to expand its flagship Chasing Greatness series, raising the standard for what a sports almanac can be.",
    media: [
      { src: "https://i.ytimg.com/vi_webp/aj0HqYYyWNs/maxresdefault.webp", kind: "video-poster" },
      { src: "https://framerusercontent.com/images/zIb9GlEyPp7Iv98UNiczmx59axM.jpg?width=2500&height=1096", bleed: true },
      { src: "https://i.ytimg.com/vi_webp/0-JPw9Vk7oA/maxresdefault.webp", kind: "video-poster" },
      { src: "https://framerusercontent.com/images/2RqxCFbgJy0JBYZWNYQ6saXCs4.jpg?width=2500&height=1096" },
      { src: "https://framerusercontent.com/images/hz0rBAeP4DV7PdwTMKrkowBzDlA.jpg?width=2500&height=1096" },
      { src: "https://framerusercontent.com/images/9goI9INdFmld3TmUSR59112b4Y.jpg?width=2500&height=1096" },
    ],
  },
  {
    slug: "social-platform",
    client: "Toldya",
    title: "Mobile App",
    thumbnail: "https://framerusercontent.com/images/zZl0gLDX8liyUKE5j2chb9RpFvg.png?scale-down-to=2048&width=2500&height=1326",
    alt: "Toldya mobile app",
    tagline: "Real-time Sports Prediction",
    description: "ToldYa is a social platform designed for real-time sports prediction. It blends the excitement of live games with interactive predictions, letting users compete, engage, and share insights as the action unfolds.",
    services: ["Product Strategy", "UX Design", "App Development", "Launch & Go-to-Market Strategy"],
    industries: "Social",
    date: "January 2023",
    outcome: "HintonX designed and delivered a full-scale, multi-platform mobile app that achieved high user engagement and was successfully acquired after launch through collaboration with global partners.",
    media: [
      { src: "https://i.ytimg.com/vi_webp/AxhQoRTHdSQ/maxresdefault.webp", kind: "video-poster" },
      { src: "https://framerusercontent.com/images/uBucigXSzUaQZbq27Wa6L6pCHVI.png?width=2500&height=1326", bleed: true },
      { src: "https://framerusercontent.com/images/gRw2zfc5KpRAt5KJNbNCpG3qlM.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/Pl4UWRwhKnWVPcHiiVHTcZuJblo.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/ZViEaKJEIz1mSVOCRq1vXDjfdo.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/vjNsbiVKlJWQrJimTkUgR1PlWKo.png?width=2500&height=1326" },
    ],
  },
  {
    slug: "innodata",
    client: "Innodata",
    title: "Custom Enterprise Software",
    thumbnail: "https://framerusercontent.com/images/d5JaN33TKoFvQ1qDjxmwInXs.png?scale-down-to=2048&width=2500&height=1326",
    alt: "Innodata enterprise software",
    tagline: "Custom Enterprise Software",
    description: "Innodata is a global data engineering company specializing in AI-powered content transformation, data curation, and knowledge process outsourcing for industries like finance, legal, and publishing.",
    services: ["UX Design", "Product Strategy"],
    industries: "Data Engineering and Artificial Intelligence",
    date: "2023–2024",
    outcome: "HintonX worked on the Admin Kit in collaboration with Zephus Limited to improve the user experience and workflow efficiency for financial researchers and analysts, refining complex task flows across search, editorial, validation, and data integration.",
    media: [{ src: "https://framerusercontent.com/images/d5JaN33TKoFvQ1qDjxmwInXs.png?scale-down-to=2048&width=2500&height=1326", bleed: true }],
  },
  {
    slug: "spectrum-management-platform",
    client: "Innovation, Science and Economic Development Canada (ISED)",
    shortClient: "ISED",
    title: "Spectrum Management Platform",
    thumbnail: "https://framerusercontent.com/images/cXWEYTAhE3oHKjRb52MQZ5ix2E.png?width=2500&height=1326",
    alt: "ISED Spectrum Cloud Platform",
    tagline: "Spectrum Management Platform",
    description: "HintonX supported the Spectrum and Telecommunications Sector in modernizing its national platform. The Spectrum Cloud User Trial was a nationwide test of the final prototype—a digital solution designed to enhance how Canada manages and regulates radio spectrum usage.",
    services: ["UX Research", "Product Strategy", "UX Design"],
    industries: "Government + Cloud Infrastructure",
    date: "",
    outcome: "The successful trial marked a critical milestone in Canada’s digital infrastructure roadmap. The insights gathered enabled ISED to move into production launch, modernizing legacy systems and increasing operational efficiency nationwide.",
    media: [{ src: "https://framerusercontent.com/images/cXWEYTAhE3oHKjRb52MQZ5ix2E.png?width=2500&height=1326", bleed: true }],
  },
  {
    slug: "cbsa-connect",
    client: "Canada Border Services Agency",
    shortClient: "CBSA",
    title: "Admin Portal + Mobile App",
    thumbnail: "https://framerusercontent.com/images/akmyrZffSqvGlSYtvpzxZWZgg.png?width=2500&height=1326",
    alt: "CBSA admin portal and mobile app",
    tagline: "Admin Portal + Mobile App",
    description: "The CBSA Mobile App project aimed to modernize how border officers access information in the field. Designed for use across airports, land crossings, and inspection zones, the mobile app delivers real-time access to shipment data, traveler information, and enforcement tools.",
    services: ["Front-End Design", "Product Strategy"],
    industries: "Government / Public Safety",
    date: "2019–2022",
    outcome: "HintonX supported the end-to-end experience design for this secure mobile platform, improving usability, accessibility compliance, and alignment with operational needs through iterative testing with border officers.",
    media: [
      { src: "https://framerusercontent.com/images/DNNFQQHl7oNYWAlL5m72zvfmwjE.png?width=2500&height=1326", bleed: true },
      { src: "https://framerusercontent.com/images/rXTW7g6ffaMlbLzZBJHvPBtwkk.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/tgvuQrrOlT08hotJXaEESKe4.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/7Fos0Ot4YA1or9xqh1JNNlOR5FE.png?width=2500&height=1326" },
    ],
  },
  {
    slug: "canada-border-services-agency",
    client: "Canada Border Services Agency",
    shortClient: "CBSA",
    title: "Enhancing Border Intelligence with Machine Learning",
    thumbnail: "https://framerusercontent.com/images/Y63ztoooToHBIkPa7aFxzznnoA.png?scale-down-to=2048&width=2500&height=1326",
    alt: "CBSA ELVIS machine-learning inspection system",
    tagline: "Enhancing Border Intelligence with Machine Learning",
    description: "The Low Value Inspection System (ELVIS) is a cutting-edge initiative developed for the Canada Border Services Agency to modernize and streamline the inspection of low-value e-commerce shipments. By leveraging machine learning, ELVIS strengthens targeting while helping officers manage growing parcel volumes.",
    services: ["UX Design", "Design System", "Product Strategy"],
    industries: "Government / Border Security",
    date: "",
    outcome: "As a UX contractor under CBSA, HintonX contributed to the experience strategy and interface design for ELVIS—aligning operational workflows with data-driven insights and supporting the integration of ML models into tools used by border officers.",
    media: [
      { src: "https://framerusercontent.com/images/Y63ztoooToHBIkPa7aFxzznnoA.png?scale-down-to=2048&width=2500&height=1326", bleed: true },
      { src: "https://framerusercontent.com/images/1UrUh10LnQlBIjNaAyqbbeJVDvg.png?width=2500&height=1326" },
      { src: "https://framerusercontent.com/images/oTARU0JuM2gpFvZjWTMPwjRTgk.png?width=2500&height=1326" },
    ],
  },
  {
    slug: "1valet",
    client: "1VALET",
    title: "Smart Building Platform",
    thumbnail: "https://framerusercontent.com/images/frLowbIPIo2RoQSDPX8lEadVVs.png?scale-down-to=2048&width=2500&height=1326",
    alt: "1VALET smart building platform",
    tagline: "Smart Building Platform",
    description: "1VALET is a Canadian smart building platform that integrates hardware, software, and services to enhance multi-family residential living.",
    services: ["Product Strategy", "UX Design", "Development"],
    industries: "Building Automation + Property Management + Smart Access Control",
    date: "2020–2021",
    outcome: "The solutions included smart intercoms, package delivery systems, resident apps, and centralized property-management tools. HintonX delivered the MVP, led product strategy and development, and supported the internal team’s successful transition to independent product ownership.",
    media: [
      { src: "https://framerusercontent.com/images/HLYPKaTP3ybY2QMu9jpafqA29U.png?width=2500&height=1326", bleed: true },
      { src: "https://framerusercontent.com/images/EcaixR4jLNKt6qcjyE7NrypE.png?width=2500&height=1321" },
      { src: "https://framerusercontent.com/images/P8pyPG4rkevfR6V21FemwwZIXU0.png?width=2500&height=1321" },
      { src: "https://framerusercontent.com/images/aKmcEyuFuwd83CmBsTCs1JD9WPg.png?width=2500&height=1321" },
      { src: "https://framerusercontent.com/images/vruuGjFDbV0yiNLQoq5p3GxCxc.png?lossless=1&width=2500&height=1321" },
    ],
  },
];

export const homeServices = [
  {
    title: "Product Design",
    body: "We believe everyone deserves exceptional user experiences—at work or at play—so we design memorable enterprise and consumer products and platforms, along with scalable design systems for seamless iteration.",
    items: ["Consumer & Enterprise Software", "CX, UX & Interaction Design", "Design Systems"],
  },
  {
    title: "Branding",
    body: "A brand is more than a logo or color scheme—it’s a complete identity. We develop unique visual and design systems, build essential brand assets, and define clear guidelines to ensure consistency across every touchpoint.",
    items: ["Brand Strategy", "Brand Architecture", "Brand Guidelines"],
  },
  {
    title: "Generative AI",
    body: "We harness generative AI to create smarter, more intuitive digital products—streamlining workflows, personalizing experiences, and setting new standards in UX design through advanced interaction models.",
    items: ["AI-Driven UX Design", "AI-Enhanced Digital Products", "Strategic AI Integration"],
  },
];

export const videoProjects = [
  ["The Legend", "Opening Sequence Teaser for the Upcoming Documentary", "iUXu4dyxbSI", "maxresdefault"],
  ["Creativity in Public Sector", "Client Adobe", "hYZgGD9qSzY", "sddefault"],
  ["The 2024 Tennis Season", "Official Book Trailer", "Kjk2cX7xaNU", "sddefault"],
  ["Adobe and Service Canada", "Promo Video", "qzKlpU0CvGM", "sddefault"],
  ["Novak Djokovic", "Year End #1 Yearbook Collection", "3mxLcNnxfNU", "sddefault"],
  ["ToldYa", "Mobile App Promo", "5OH6sWLEL8c", "sddefault"],
  ["100 Mobile", "Message App Promo", "bmYRh4Yy1nk", "sddefault"],
].map(([title, subtitle, id, quality]) => ({ title, subtitle, src: `https://i.ytimg.com/vi_webp/${id}/${quality}.webp` }));
